### PR TITLE
Added Vectorized/chunked SMAPE calculation and Histogram based JSD calculation

### PR DESCRIPTION
**Pull request by amiiralii**
Added Vectorized/chunked SMAPE calculation and Histogram-based JSD calculation.

** The parameters of the SMAPE method can be datasets themselves, not necessarily the distribution. Am I Right?

### CODE REVIEW

**Comment by yrahul3910** [comment]
@amiiralii Looks good. Please fix the above issues--I can't merge otherwise. I recommend using `ruff` to auto-fix most stuff. There's an unused variable warning, which you can fix by renaming to `_`.

**Comment by yrahul3910** [comment]
You can ignore the long lines parts--that should've been set to 120.

**Comment by amiiralii** [comment]
I checked it with Ruff but did not find any issues. However, I updated the code regarding each bug mentioned above.
Tell me if there are any more issues.
Thanks,

**Comment by yrahul3910** [comment]
I see, I think it's just complaining about the assert statement. I think that's fine, so I'll override and merge. Thanks!

**Pull request merged**
